[phases.setup]
nixPkgs = ["nodejs_20", "openssl_3"]
aptPkgs = ["openssl", "libssl3", "libssl-dev"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --accept-data-loss", "npm run build"]

[start]
cmd = "npm start"
